#ifndef INPUT_METHOD_TOKENS_H
#define INPUT_METHOD_TOKENS_H

#define AND_TOKEN "&&"
#define OR_TOKEN "||"
#define KEY_TOKEN "KEY("
#define MODIFIER_KEY_TOKEN "MODIFIERKEY("


#endif // INPUT_METHOD_TOKENS_H
